<?php
echo "<!DOCTYPE html>\n";
echo '<html lang="ja">'."\n";
echo "<head>\n";
echo '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">'."\n";
echo "<title>ログイン画面</title>\n";
echo "</head>\n";
    echo "<body>\n";
        echo '<form method="post" action="https://atarime.cs.tohoku-gakuin.ac.jp/~akimiki/page_top.php">'."\n";
        echo "<center>\n";
        echo '<table width="60%">'."\n";
        echo "<tr>\n";
        echo "<td>\n";
        echo "<center>\n";
            echo '<h1><font size="7">秋山のトップページ</font></h1>'."\n";
        echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
        echo "<td>\n";
        echo "<center>\n";
        echo '<table>'."\n";
            echo "<tr>\n";
                echo '<td><font size="6">ユーザ名</font></td>'."\n";
                echo '<td><input required type="text" name="v1" style="width: 200px; height: 30px;" required></td>'."\n";
            echo "</tr>\n";
            echo "<tr>\n";
                echo '<td><font size="6">パスワード</font></td>'."\n";
                echo '<td><input required type ="password" name="v2" style="width: 200px; height: 30px;" required></td>'."\n";
            echo "</tr>\n";
            echo "<tr>\n";
            echo "<td></td>\n";
                echo "<td align=right>\n";
                echo "<br />\n";
                echo '<input type="submit" value="ログイン" style="width:100px;height:50px">'."\n";
                echo "</td>\n";
            echo "</tr>\n";
        echo "</table>\n";
        echo "</center>\n";
        echo "</td>\n";
        echo "</tr>\n";
        echo "</table>\n";
        echo "</center>\n";
        echo "</form>\n";
    echo "</body>\n";
echo "</html>\n";
?>